-- 029_eqemu_full_schemas.sql
-- Full EQEmu schemas for all remaining tables with column mismatches.
-- Exported from akk-stack MariaDB and converted to PostgreSQL.

DROP VIEW IF EXISTS spawn2 CASCADE;
DROP TABLE IF EXISTS spawn_points CASCADE;
DROP TABLE IF EXISTS spawn2 CASCADE;
spawn2
CREATE TABLE spawn2 (
  id INTEGER NOT NULL
  spawngroupID INTEGER NOT NULL DEFAULT 0
  zone TEXT DEFAULT NULL
  version SMALLINT NOT NULL DEFAULT 0
  x float(14,6) NOT NULL DEFAULT 0.000000
  y float(14,6) NOT NULL DEFAULT 0.000000
  z float(14,6) NOT NULL DEFAULT 0.000000
  heading float(14,6) NOT NULL DEFAULT 0.000000
  respawntime INTEGER NOT NULL DEFAULT 0
  variance INTEGER NOT NULL DEFAULT 0
  pathgrid INTEGER NOT NULL DEFAULT 0
  path_when_zone_idle SMALLINT NOT NULL DEFAULT 0
  _condition INTEGER NOT NULL DEFAULT 0
  cond_value INTEGER NOT NULL DEFAULT 1
  animation SMALLINT NOT NULL DEFAULT 0
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW spawn_points AS SELECT * FROM spawn2;

DROP VIEW IF EXISTS spawngroup CASCADE;
DROP TABLE IF EXISTS spawn_groups CASCADE;
DROP TABLE IF EXISTS spawngroup CASCADE;
spawngroup
CREATE TABLE spawngroup (
  id INTEGER NOT NULL
  name TEXT NOT NULL DEFAULT ''
  spawn_limit SMALLINT NOT NULL DEFAULT 0
  dist REAL NOT NULL DEFAULT 0
  max_x REAL NOT NULL DEFAULT 0
  min_x REAL NOT NULL DEFAULT 0
  max_y REAL NOT NULL DEFAULT 0
  min_y REAL NOT NULL DEFAULT 0
  delay INTEGER NOT NULL DEFAULT 45000
  mindelay INTEGER NOT NULL DEFAULT 15000
  despawn SMALLINT NOT NULL DEFAULT 0
  despawn_timer INTEGER NOT NULL DEFAULT 100
  wp_spawns SMALLINT NOT NULL DEFAULT 0
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW spawn_groups AS SELECT * FROM spawngroup;

DROP VIEW IF EXISTS spawnentry CASCADE;
DROP TABLE IF EXISTS spawn_entries CASCADE;
DROP TABLE IF EXISTS spawnentry CASCADE;
spawnentry
CREATE TABLE spawnentry (
  spawngroupID INTEGER NOT NULL DEFAULT 0
  npcID INTEGER NOT NULL DEFAULT 0
  chance SMALLINT NOT NULL DEFAULT 0
  condition_value_filter INTEGER NOT NULL DEFAULT 1
  min_time SMALLINT NOT NULL DEFAULT 0
  max_time SMALLINT NOT NULL DEFAULT 0
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW spawn_entries AS SELECT * FROM spawnentry;

DROP VIEW IF EXISTS loottable CASCADE;
DROP TABLE IF EXISTS loot_tables CASCADE;
DROP TABLE IF EXISTS loottable CASCADE;
loottable
CREATE TABLE loottable (
  id INTEGER NOT NULL
  name TEXT NOT NULL DEFAULT ''
  mincash INTEGER NOT NULL DEFAULT 0
  maxcash INTEGER NOT NULL DEFAULT 0
  avgcoin INTEGER NOT NULL DEFAULT 0
  done SMALLINT NOT NULL DEFAULT 0
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW loot_tables AS SELECT * FROM loottable;

DROP VIEW IF EXISTS lootdrop CASCADE;
DROP TABLE IF EXISTS loot_drops CASCADE;
DROP TABLE IF EXISTS lootdrop CASCADE;
lootdrop
CREATE TABLE lootdrop (
  id INTEGER NOT NULL
  name TEXT NOT NULL DEFAULT ''
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW loot_drops AS SELECT * FROM lootdrop;

DROP VIEW IF EXISTS loottable_entries CASCADE;
DROP TABLE IF EXISTS loot_table_entries CASCADE;
DROP TABLE IF EXISTS loottable_entries CASCADE;
loottable_entries
CREATE TABLE loottable_entries (
  loottable_id INTEGER NOT NULL DEFAULT 0
  lootdrop_id INTEGER NOT NULL DEFAULT 0
  multiplier SMALLINT NOT NULL DEFAULT 1
  droplimit SMALLINT NOT NULL DEFAULT 0
  mindrop SMALLINT NOT NULL DEFAULT 0
  probability REAL NOT NULL DEFAULT 100
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW loot_table_entries AS SELECT * FROM loottable_entries;

DROP VIEW IF EXISTS lootdrop_entries CASCADE;
DROP TABLE IF EXISTS loot_drop_entries CASCADE;
DROP TABLE IF EXISTS lootdrop_entries CASCADE;
lootdrop_entries
CREATE TABLE lootdrop_entries (
  lootdrop_id INTEGER NOT NULL DEFAULT 0
  item_id INTEGER NOT NULL DEFAULT 0
  item_charges SMALLINT NOT NULL DEFAULT 1
  equip_item SMALLINT NOT NULL DEFAULT 0
  chance REAL NOT NULL DEFAULT 1
  disabled_chance REAL NOT NULL DEFAULT 0
  trivial_min_level SMALLINT NOT NULL DEFAULT 0
  trivial_max_level SMALLINT NOT NULL DEFAULT 0
  multiplier SMALLINT NOT NULL DEFAULT 1
  npc_min_level SMALLINT NOT NULL DEFAULT 0
  npc_max_level SMALLINT NOT NULL DEFAULT 0
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW loot_drop_entries AS SELECT * FROM lootdrop_entries;

DROP VIEW IF EXISTS merchantlist CASCADE;
DROP TABLE IF EXISTS merchant_lists CASCADE;
DROP TABLE IF EXISTS merchantlist CASCADE;
merchantlist
CREATE TABLE merchantlist (
  merchantid INTEGER NOT NULL DEFAULT 0
  slot INTEGER NOT NULL DEFAULT 0
  item INTEGER NOT NULL DEFAULT 0
  faction_required SMALLINT NOT NULL DEFAULT -100
  level_required SMALLINT NOT NULL DEFAULT 0
  min_status SMALLINT NOT NULL DEFAULT 0
  max_status SMALLINT NOT NULL DEFAULT 255
  alt_currency_cost SMALLINT NOT NULL DEFAULT 0
  classes_required INTEGER NOT NULL DEFAULT 65535
  probability INTEGER NOT NULL DEFAULT 100
  bucket_name TEXT NOT NULL DEFAULT ''
  bucket_value TEXT NOT NULL DEFAULT ''
  bucket_comparison SMALLINT DEFAULT 0
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW merchant_lists AS SELECT * FROM merchantlist;

DROP TABLE IF EXISTS zone_points CASCADE;
zone_points
CREATE TABLE zone_points (
  id INTEGER NOT NULL
  zone TEXT DEFAULT NULL
  version INTEGER NOT NULL DEFAULT 0
  number SMALLINT NOT NULL DEFAULT 1
  y REAL NOT NULL DEFAULT 0
  x REAL NOT NULL DEFAULT 0
  z REAL NOT NULL DEFAULT 0
  heading REAL NOT NULL DEFAULT 0
  target_y REAL NOT NULL DEFAULT 0
  target_x REAL NOT NULL DEFAULT 0
  target_z REAL NOT NULL DEFAULT 0
  target_heading REAL NOT NULL DEFAULT 0
  zoneinst SMALLINT DEFAULT 0
  target_zone_id INTEGER NOT NULL DEFAULT 0
  target_instance INTEGER NOT NULL DEFAULT 0
  buffer REAL DEFAULT 0
  client_version_mask INTEGER NOT NULL DEFAULT 4294967295
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  is_virtual SMALLINT NOT NULL DEFAULT 0
  height INTEGER NOT NULL DEFAULT 0
  width INTEGER NOT NULL DEFAULT 0
  PRIMARY KEY (id) USING BTREE
);;

DROP VIEW IF EXISTS npc_spells CASCADE;
DROP TABLE IF EXISTS npc_spell_lists CASCADE;
DROP TABLE IF EXISTS npc_spells CASCADE;
npc_spells
CREATE TABLE npc_spells (
  id INTEGER NOT NULL
  name tinytext DEFAULT NULL
  parent_list INTEGER NOT NULL DEFAULT 0
  attack_proc SMALLINT NOT NULL DEFAULT -1
  proc_chance SMALLINT NOT NULL DEFAULT 3
  range_proc SMALLINT NOT NULL DEFAULT -1
  rproc_chance SMALLINT NOT NULL DEFAULT 0
  defensive_proc SMALLINT NOT NULL DEFAULT -1
  dproc_chance SMALLINT NOT NULL DEFAULT 0
  fail_recast INTEGER NOT NULL DEFAULT 0
  engaged_no_sp_recast_min INTEGER NOT NULL DEFAULT 0
  engaged_no_sp_recast_max INTEGER NOT NULL DEFAULT 0
  engaged_b_self_chance SMALLINT NOT NULL DEFAULT 0
  engaged_b_other_chance SMALLINT NOT NULL DEFAULT 0
  engaged_d_chance SMALLINT NOT NULL DEFAULT 0
  pursue_no_sp_recast_min INTEGER NOT NULL DEFAULT 0
  pursue_no_sp_recast_max INTEGER NOT NULL DEFAULT 0
  pursue_d_chance SMALLINT NOT NULL DEFAULT 0
  idle_no_sp_recast_min INTEGER NOT NULL DEFAULT 0
  idle_no_sp_recast_max INTEGER NOT NULL DEFAULT 0
  idle_b_chance SMALLINT NOT NULL DEFAULT 0
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW npc_spell_lists AS SELECT * FROM npc_spells;

DROP VIEW IF EXISTS npc_spells_entries CASCADE;
DROP TABLE IF EXISTS npc_spell_entries CASCADE;
DROP TABLE IF EXISTS npc_spells_entries CASCADE;
npc_spells_entries
CREATE TABLE npc_spells_entries (
  id INTEGER NOT NULL
  npc_spells_id INTEGER NOT NULL DEFAULT 0
  spellid SMALLINT NOT NULL DEFAULT 0
  type INTEGER NOT NULL DEFAULT 0
  minlevel SMALLINT NOT NULL DEFAULT 0
  maxlevel SMALLINT NOT NULL DEFAULT 255
  manacost SMALLINT NOT NULL DEFAULT -1
  recast_delay INTEGER NOT NULL DEFAULT -1
  priority SMALLINT NOT NULL DEFAULT 0
  resist_adjust INTEGER DEFAULT NULL
  min_hp SMALLINT DEFAULT 0
  max_hp SMALLINT DEFAULT 0
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;
CREATE OR REPLACE VIEW npc_spell_entries AS SELECT * FROM npc_spells_entries;

DROP TABLE IF EXISTS npc_emotes CASCADE;
npc_emotes
CREATE TABLE npc_emotes (
  id INTEGER NOT NULL
  emoteid INTEGER NOT NULL DEFAULT 0
  event_ SMALLINT NOT NULL DEFAULT 0
  type SMALLINT NOT NULL DEFAULT 0
  text TEXT NOT NULL
  PRIMARY KEY (id)
);;

DROP VIEW IF EXISTS grid CASCADE;
DROP TABLE IF EXISTS patrol_grids CASCADE;
DROP TABLE IF EXISTS grid CASCADE;
grid
CREATE TABLE grid (
  id INTEGER NOT NULL DEFAULT 0
  zoneid INTEGER NOT NULL DEFAULT 0
  type INTEGER NOT NULL DEFAULT 0
  type2 INTEGER NOT NULL DEFAULT 0
  PRIMARY KEY (zoneid,id)
);;
CREATE OR REPLACE VIEW patrol_grids AS SELECT * FROM grid;

DROP VIEW IF EXISTS grid_entries CASCADE;
DROP TABLE IF EXISTS patrol_waypoints CASCADE;
DROP TABLE IF EXISTS grid_entries CASCADE;
grid_entries
CREATE TABLE grid_entries (
  gridid INTEGER NOT NULL DEFAULT 0
  zoneid INTEGER NOT NULL DEFAULT 0
  number INTEGER NOT NULL DEFAULT 0
  x REAL NOT NULL DEFAULT 0
  y REAL NOT NULL DEFAULT 0
  z REAL NOT NULL DEFAULT 0
  heading REAL NOT NULL DEFAULT 0
  pause INTEGER NOT NULL DEFAULT 0
  centerpoint SMALLINT NOT NULL DEFAULT 0
  PRIMARY KEY (zoneid,gridid,number)
);;
CREATE OR REPLACE VIEW patrol_waypoints AS SELECT * FROM grid_entries;

DROP TABLE IF EXISTS pets CASCADE;
pets
CREATE TABLE pets (
  id INTEGER NOT NULL
  type TEXT NOT NULL DEFAULT ''
  petpower INTEGER NOT NULL DEFAULT 0
  npcID INTEGER NOT NULL DEFAULT 0
  temp SMALLINT NOT NULL DEFAULT 0
  petcontrol SMALLINT NOT NULL DEFAULT 0
  petnaming SMALLINT NOT NULL DEFAULT 0
  monsterflag SMALLINT NOT NULL DEFAULT 0
  equipmentset INTEGER NOT NULL DEFAULT -1
  PRIMARY KEY (id)
);;

DROP TABLE IF EXISTS ground_spawns CASCADE;
ground_spawns
CREATE TABLE ground_spawns (
  id INTEGER NOT NULL
  zoneid INTEGER NOT NULL DEFAULT 0
  version SMALLINT NOT NULL DEFAULT 0
  max_x REAL NOT NULL DEFAULT 2000
  max_y REAL NOT NULL DEFAULT 2000
  max_z REAL NOT NULL DEFAULT 10000
  min_x REAL NOT NULL DEFAULT -2000
  min_y REAL NOT NULL DEFAULT -2000
  heading REAL NOT NULL DEFAULT 0
  name TEXT NOT NULL DEFAULT ''
  item INTEGER NOT NULL DEFAULT 0
  max_allowed INTEGER NOT NULL DEFAULT 1
  comment TEXT NOT NULL DEFAULT ''
  respawn_timer INTEGER NOT NULL DEFAULT 300
  fix_z SMALLINT NOT NULL DEFAULT 1
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;

DROP TABLE IF EXISTS object CASCADE;
object
CREATE TABLE object (
  id INTEGER NOT NULL
  zoneid INTEGER NOT NULL DEFAULT 0
  version SMALLINT NOT NULL DEFAULT 0
  xpos REAL NOT NULL DEFAULT 0
  ypos REAL NOT NULL DEFAULT 0
  zpos REAL NOT NULL DEFAULT 0
  heading REAL NOT NULL DEFAULT 0
  itemid INTEGER NOT NULL DEFAULT 0
  charges SMALLINT NOT NULL DEFAULT 0
  objectname TEXT DEFAULT NULL
  type INTEGER NOT NULL DEFAULT 0
  icon INTEGER NOT NULL DEFAULT 0
  size_percentage REAL NOT NULL DEFAULT 0
  unknown24 INTEGER NOT NULL DEFAULT 0
  unknown60 INTEGER NOT NULL DEFAULT 0
  unknown64 INTEGER NOT NULL DEFAULT 0
  unknown68 INTEGER NOT NULL DEFAULT 0
  unknown72 INTEGER NOT NULL DEFAULT 0
  unknown76 INTEGER NOT NULL DEFAULT 0
  unknown84 INTEGER NOT NULL DEFAULT 0
  size REAL NOT NULL DEFAULT 100
  solid_type INTEGER NOT NULL DEFAULT 0
  incline INTEGER NOT NULL DEFAULT 0
  tilt_x REAL NOT NULL DEFAULT 0
  tilt_y REAL NOT NULL DEFAULT 0
  display_name TEXT DEFAULT NULL
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;

DROP TABLE IF EXISTS traps CASCADE;
traps
CREATE TABLE traps (
  id INTEGER NOT NULL
  zone TEXT NOT NULL DEFAULT ''
  version SMALLINT NOT NULL DEFAULT 0
  x INTEGER NOT NULL DEFAULT 0
  y INTEGER NOT NULL DEFAULT 0
  z INTEGER NOT NULL DEFAULT 0
  chance SMALLINT NOT NULL DEFAULT 0
  maxzdiff REAL NOT NULL DEFAULT 0
  radius REAL NOT NULL DEFAULT 0
  effect INTEGER NOT NULL DEFAULT 0
  effectvalue INTEGER NOT NULL DEFAULT 0
  effectvalue2 INTEGER NOT NULL DEFAULT 0
  message TEXT NOT NULL DEFAULT ''
  skill INTEGER NOT NULL DEFAULT 0
  level INTEGER NOT NULL DEFAULT 1
  respawn_time INTEGER NOT NULL DEFAULT 60
  respawn_var INTEGER NOT NULL DEFAULT 0
  triggered_number SMALLINT NOT NULL DEFAULT 0
  group SMALLINT NOT NULL DEFAULT 0
  despawn_when_triggered SMALLINT NOT NULL DEFAULT 0
  undetectable SMALLINT NOT NULL DEFAULT 0
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;

DROP TABLE IF EXISTS tradeskill_recipe CASCADE;
tradeskill_recipe
CREATE TABLE tradeskill_recipe (
  id INTEGER NOT NULL
  name TEXT NOT NULL DEFAULT ''
  tradeskill SMALLINT NOT NULL DEFAULT 0
  skillneeded SMALLINT NOT NULL DEFAULT 0
  trivial SMALLINT NOT NULL DEFAULT 0
  nofail SMALLINT NOT NULL DEFAULT 0
  replace_container SMALLINT NOT NULL DEFAULT 0
  notes tinytext DEFAULT NULL
  must_learn SMALLINT NOT NULL DEFAULT 0
  learned_by_item_id INTEGER NOT NULL DEFAULT 0
  quest SMALLINT NOT NULL DEFAULT 0
  enabled SMALLINT NOT NULL DEFAULT 1
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id) USING BTREE
);;

DROP TABLE IF EXISTS tradeskill_recipe_entries CASCADE;
tradeskill_recipe_entries
CREATE TABLE tradeskill_recipe_entries (
  id INTEGER NOT NULL
  recipe_id INTEGER NOT NULL DEFAULT 0
  item_id INTEGER NOT NULL DEFAULT 0
  successcount SMALLINT NOT NULL DEFAULT 0
  failcount SMALLINT NOT NULL DEFAULT 0
  componentcount SMALLINT NOT NULL DEFAULT 1
  salvagecount SMALLINT NOT NULL DEFAULT 0
  iscontainer SMALLINT NOT NULL DEFAULT 0
  PRIMARY KEY (id) USING BTREE
);;

DROP TABLE IF EXISTS blocked_spells CASCADE;
blocked_spells
CREATE TABLE blocked_spells (
  id INTEGER NOT NULL
  spellid INTEGER NOT NULL DEFAULT 0
  type SMALLINT NOT NULL DEFAULT 0
  zoneid INTEGER NOT NULL DEFAULT 0
  x REAL NOT NULL DEFAULT 0
  y REAL NOT NULL DEFAULT 0
  z REAL NOT NULL DEFAULT 0
  x_diff REAL NOT NULL DEFAULT 0
  y_diff REAL NOT NULL DEFAULT 0
  z_diff REAL NOT NULL DEFAULT 0
  message TEXT NOT NULL DEFAULT ''
  description TEXT NOT NULL DEFAULT ''
  min_expansion SMALLINT NOT NULL DEFAULT -1
  max_expansion SMALLINT NOT NULL DEFAULT -1
  content_flags TEXT DEFAULT NULL
  content_flags_disabled TEXT DEFAULT NULL
  PRIMARY KEY (id)
);;

